#!/bin/bash -e

LOCK_FILE=/var/lock/9_firsttime.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

# Sleep to allow MYSQL server to come up
sleep 15

## Create tables
sh -c "cd /opt/librenms && php /opt/librenms/build-base.php"

# Create initial user
php /opt/librenms/adduser.php manager friend 10

# Create Oxidized user if wanted and create API token for the user
if [ -n "${OXIDIZED_USERNAME}" ]; then
    # TODO Need to randomise the password for security
    php /opt/librenms/adduser.php ${OXIDIZED_USERNAME} oxidized 10
    sh -c "/opt/librenms/write_oxidized_api_token.py"
fi

touch "$LOCK_FILE"
