#!/bin/bash -e

LOCK_FILE=/var/lock/9_firsttime.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

# Sleep to allow MYSQL server to come up
sleep 15

## Create tables
sh -c "cd /opt/librenms && php /opt/librenms/build-base.php"

# Create initial user
php /opt/librenms/adduser.php manager friend 10 daniel.olynsma@alliedtelesis.co.nz
php /opt/librenms/adduser.php oxidized oxidized 10 daniel.olynsma@alliedtelesis.co.nz

touch "$LOCK_FILE"
