#!/bin/bash -e

LOCK_FILE=/var/lock/9_firsttime.lock

if [ -f "$LOCK_FILE" ]; then
	exit 0
fi

# Sleep to allow MYSQL server to come up
sleep 15

## Create tables
sh -c "cd /opt/librenms && php /opt/librenms/build-base.php"

# Create initial user
php /opt/librenms/adduser.php manager friend 10

# Create Oxidized user if wanted and create API token for the user
if [ -n "${OXIDIZED_USERNAME}" ]; then
    # TODO Need to randomise the password for security
    php /opt/librenms/adduser.php ${OXIDIZED_USERNAME} oxidized 10
    sh -c "/opt/librenms/write_oxidized_api_token.py"
fi

# Scan networks and populate libreNMS
if [ -n "${SCAN_ON_FIRST_STARTUP}" ]; then
    if [ "$SCAN_ON_FIRST_STARTUP" = "true" ]; then
	    sh -c "/opt/librenms/snmp-scan.py"
	    # These two scripts do take a while.  But only run once
	    #sh -c "/opt/librenms/discovery-wrapper.py 16"
	    #sh -c "/opt/librenms/poller-wrapper.py 16"
    fi
fi

touch "$LOCK_FILE"
