#!/bin/bash
set -e

# start apache to serve block.html file
sudo /etc/init.d/apache2 start

echo "running startSquidGuard with WPAD_IP=${WPAD_IP} WPAD_NOPROXY_NET=${WPAD_NOPROXY_NET} WPAD_NOPROXY_MASK=${WPAD_NOPROXY_MASK}"

if [  "${WPAD_IP}" != "" ]; then
	sed 's/{{WPAD_IP}}/'"${WPAD_IP}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_NET}}/'"${WPAD_NOPROXY_NET}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_MASK}}/'"${WPAD_NOPROXY_MASK}"'/' -i /var/www/html/wpad.dat

	# start apache to serve wpad.dat file
	sudo /etc/init.d/apache2 restart
fi

# run original squid start script
exec /sbin/entrypoint.sh
