version: '2'

services:
  librenms:
    build:
      context: librenms
    ports:
      - "80:80"
    volumes:
      - oxidized_token:/tmp/token
#      - /my/persistent/directory/logs:/opt/librenms/logs
#      - /my/persistent/directory/rrd:/opt/librenms/rrd
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - POLLERS=16
      - BASE_URL=${BASE_URL}
      - ENABLE_SYSLOG=false
      - TZ=${TZ}
      - OXIDIZED_USERNAME=oxidized
      - SCAN_ON_FIRST_STARTUP=true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    command: --sql-mode=""
    ports:
      - "3306:3306"
#    volumes:
#      - /my/persistent/directory/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

 ##### Plugins
  # Config backup
  oxidized:
    build:
      context: oxidized
    ports:
      - 8888:8888/tcp
    environment:
      - CONFIG_RELOAD_INTERVAL=600
      - TZ=${TZ}
    depends_on:
      - librenms
    volumes:
      - oxidized_token:/tmp/token
      - /opt/docker/librenms/oxidized:/root/.config/oxidized

  # ssh terminal server
  gateone:
    build:
      context: gateone
    ports:
      - "8000:8000"
    volumes:
      - oxidized_token:/tmp/token

volumes:
  oxidized_token:
