version: '2'

services:
  librenms:
    # image: jarischaefer/docker-librenms
    build:
      context: librenms
    ports:
      - "80:80"
#    volumes:
#      - /my/persistent/directory/logs:/opt/librenms/logs
#      - /my/persistent/directory/rrd:/opt/librenms/rrd
    environment:
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASS=secret
      - POLLERS=16
      - BASE_URL=http://localhost
      - ENABLE_SYSLOG=false
      - TZ="Pacific/Auckland"
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.6
#    build:
#      context: mysql
    command: --sql-mode=""
    networks:
      - backend
    ports:
      - "3306:3306"
#    volumes:
#      - /my/persistent/directory/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # These values must match the DB{NAME|USER|PASS} in libreNMS container or server
      - MYSQL_DATABASE=librenms
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=secret

  oxidized:
    # image: oxidized/oxidized:latest
    build:
      context: oxidized
    networks:
      - backend
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    depends_on:
      - librenms
    volumes:
      - /opt/oxidized:/root/.config/oxidized

networks:
  backend:
