version: '2'

services:
  librenms:
    build:
      context: librenms
    ports:
      - "80:80"
    volumes:
      - oxidized_token:/tmp/token
#      - /my/persistent/directory/logs:/opt/librenms/logs
#      - /my/persistent/directory/rrd:/opt/librenms/rrd
    environment:
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASS=secret
      - POLLERS=16
      - BASE_URL=http://localhost
      - ENABLE_SYSLOG=false
      - TZ="Pacific/Auckland"
      - OXIDIZED_USERNAME=oxidized
      - SCAN_ON_FIRST_STARTUP=true
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.6
    command: --sql-mode=""
    networks:
      - backend
    ports:
      - "3306:3306"
#    volumes:
#      - /my/persistent/directory/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # These values must match the DB{NAME|USER|PASS} in libreNMS container or server
      - MYSQL_DATABASE=librenms
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=secret

 ##### Plugins
  # Config backup
  oxidized:
    build:
      context: oxidized
    networks:
      - backend
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    depends_on:
      - librenms
    volumes:
      - oxidized_token:/tmp/token
      - /opt/docker/librenms/oxidized:/root/.config/oxidized

  # ssh terminal server
  gateone:
    build:
      context: gateone
    networks:
      - backend
    ports:
      - "8000:8000"

networks:
  backend:

volumes:
  oxidized_token:
