version: '2'

services:
  librenms:
    build:
      context: librenms
    ports:
      - "80:80"
      - "514:514"
      - "514:514/udp"
    volumes:
      - oxidized_token:/tmp/token
      - librenms_logs:/opt/librenms/logs
      - librenms_rrd:/opt/librenms/rrd
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - POLLERS=16
      - BASE_URL=${BASE_URL}
      - ENABLE_SYSLOG=false
      - APP_KEY=${APP_KEY}
      - TZ=${TZ}
      - OXIDIZED_USERNAME=oxidized
      - SCAN_ON_FIRST_STARTUP=true
      - DAILY_ON_STARTUP=true
      - ENABLE_SYSLOG=true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    command: --sql-mode=""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TZ}

  mysqladmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

 ##### Plugins
  # Config backup
  oxidized:
    build:
      context: oxidized
    ports:
      - 8888:8888/tcp
    environment:
      - CONFIG_RELOAD_INTERVAL=600
      - TZ=${TZ}
    depends_on:
      - librenms
    volumes:
      - oxidized_token:/tmp/token
      - oxidized_config:/root/.config/oxidized

#  # ssh terminal server
#  gateone:
#    build:
#      context: gateone
#    ports:
#      - "8000:8000"
#    environment:
#      # Not sure if the container understands this variable
#      - TZ=${TZ}
#    volumes:
#      - oxidized_token:/tmp/token

volumes:
  librenms_logs:
  librenms_rrd:
  mysql_data:
  oxidized_config:
  oxidized_token:
